spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp?createDatabaseIfNotExist=true
    username: root
    password: task123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: vanisrimurugan2531@gmail.com
    password: oitzliidhpxlmvfo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            ssl:
              trust: smtp.gmail.com
